Update setup_model.py
Fixes fringe cases where rmknot was causing the program to crash. Example below:

Traceback (most recent call last):
  File "/Volumes/SeaJade 2 Backup/ONC/Programs/GARPOS-MCMC/bin/GARPOS_mcmc_v1.0.0.py", line 180, in <module>
    knots = make_knots(shots, spdeg, knotintervals)
  File "/Volumes/SeaJade 2 Backup/ONC/Programs/GARPOS-MCMC/bin/garpos_mcmc_v100/setup_model.py", line 121, in make_knots
    knots[k] = np.delete(knots[k], rmknot)
  File "<__array_function__ internals>", line 6, in delete
  File "/Users/jesse/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4552, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type